#+STARTUP: overview
* 15 variable
*** primitive: x^15 + x + 1
*** points: 1057
*** orbits
* 21 variable
*** primitive: x^21 + x^2 + 1
*** points: 16513

* abstract

Search for High-Nonlinearity Boolean Functions:
-----------------------------------------------
High non-linearity boolean functions have been a topic of practical interest in cryptography because of their use in S-boxes. They help ciphers resist linear cryptanalysis. Theoretically, obtaining nonlinearity greater than the Bent-Concatenation bound for functions with odd number of variables has been a difficult combinatorial search problem. In 1983, Patterson and Wiedemann proved a lower bound on the covering radius of first order Reed-Muller codes of size 2^15. This also provided boolean functions on 15 variables with non-linearity greater than the Bent-Concatenation bound. Further research along similar lines has been carried out to find such functions on larger number of variables. We want to explore the Patterson-Wiedemann construction in detail, and study the integer linear programming problem that results from it. Like it's connection to the walsh spectrum, using the inverse of the constraint matrix to find near-boolean solutions, and exhaustively solving smaller ilp's obtained by grouping orbits together.

* TODO
** grid.c, draw.c
*** remove SDL-interaction from grid.c;
*** sob draw.c te hobe
*** draw.c: bresenham circle drawing
** asol orbit ?
** plane.c
*** draw call -> grid call



3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 21 0 0 0 0 21 0 0 0 0 0 0 0 0 0 0 0 0 0 21 21 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 21 21 0 


0 7 0 0 0 0 0 0 0 0 0 7 14 0 0 0 7 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 7 7 0 7 7 7 0 0 0 0 0 0 0 0 0 7 7 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 7 0 7 0 0 0 0 0 0 0 0 3 


0 0 0 0 0 7 0 7 0 0 0 0 0 0 0 0 7 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 7 0 7 0 0 0 0 7 0 0 7 0 0 0 0 7 0 0 0 0 7 7 0 0 0 7 0 0 0 7 0 0 0 3 0 0 0 0 0 0 0 0 14 7 0 0 0 0 0 7 0 0 0 0 0 

